name: PlotContests
version: 0.2.0
main: just.plotcontests.Contests
author: PureGero
api-version: 1.13
depend: [JustPlots]
commands:
    contest:
        description: Plot contests command.
        aliases: [contests, c]
        permission: contest
    contestjudge:
        description: Plot contests judge command.
        aliases: [cjudge, cj]
        permission: contest.judge
permissions:
    contest:
        default: true
    contest.highvote:
        default: op
    contest.judge:
        default: op